In [1]:
# import numpy library

import numpy as np 

In [2]:
# Create a numpy array

a = np.array([0, 1, 2, 3, 4])
a

array([0, 1, 2, 3, 4])

In [3]:
# Print each element

print("a[0]:", a[0])
print("a[1]:", a[1])
print("a[2]:", a[2])
print("a[3]:", a[3])
print("a[4]:", a[4])

a[0]: 0
a[1]: 1
a[2]: 2
a[3]: 3
a[4]: 4


In [4]:
# Check the type of the array

type(a)

numpy.ndarray

In [5]:
# Check the type of the values stored in numpy array

a.dtype

dtype('int32')

In [7]:
# Create numpy array

c = np.array([20, 1, 2, 3, 4])
c

array([20,  1,  2,  3,  4])

In [8]:
# Assign the first element to 100

c[0] = 100
c

array([100,   1,   2,   3,   4])

In [9]:
# Assign the 5th element to 0

c[4] = 0
c

array([100,   1,   2,   3,   0])

In [10]:
# Slicing the numpy array

d = c[1:4]
d

array([1, 2, 3])

In [11]:
# Set the fourth element and fifth element to 300 and 400

c[3:5] = 300, 400
c

array([100,   1,   2, 300, 400])

In [12]:
# Create the index list

select = [0, 2, 3]

In [13]:
# Use List to select elements

d = c[select]
d

array([100,   2, 300])

In [14]:
# Assign the specified elements to new value

c[select] = 100000
c

array([100000,      1, 100000, 100000,    400])

In [15]:
# Get the size of numpy array

c.size

5

In [16]:
# Get the number of dimensions of numpy array

c.ndim

1

In [17]:
# Get the shape/size of numpy array

c.shape

(5,)

In [18]:
# Get the mean of numpy array

mean = c.mean()
mean

60080.2

In [19]:
# Get the biggest value in the numpy array

max_c = c.max()
max_c

100000

In [20]:
# Get the smallest value in the numpy array

min_c = c.min()
min_c

1

In [ ]:
#Arrays


In [21]:
u = np.array([1, 0])
u

array([1, 0])

In [23]:
v = np.array([0, 1])
v

array([0, 1])

In [24]:
# Numpy Array Addition

z = u + v
z

array([1, 1])

In [26]:
a = 2 * u
a

array([2, 0])

In [27]:
z = u * v
z

array([0, 0])

In [28]:
# Calculate the dot product

np.dot(u, v)

0

In [29]:
# Create the numpy array in radians

x = np.array([0, np.pi/2 , np.pi])

In [30]:
# Calculate the sin of each elements

y = np.sin(x)
y

array([0.0000000e+00, 1.0000000e+00, 1.2246468e-16])

In [31]:
# Makeup a numpy array within [-2, 2] and 9 elements

np.linspace(-2, 2, num=9)

array([-2. , -1.5, -1. , -0.5,  0. ,  0.5,  1. ,  1.5,  2. ])

In [35]:
# Makeup a numpy array within [0, 2π] and 100 elements 

x = np.linspace(0, 2*np.pi, num=100)
x

array([0.        , 0.06346652, 0.12693304, 0.19039955, 0.25386607,
       0.31733259, 0.38079911, 0.44426563, 0.50773215, 0.57119866,
       0.63466518, 0.6981317 , 0.76159822, 0.82506474, 0.88853126,
       0.95199777, 1.01546429, 1.07893081, 1.14239733, 1.20586385,
       1.26933037, 1.33279688, 1.3962634 , 1.45972992, 1.52319644,
       1.58666296, 1.65012947, 1.71359599, 1.77706251, 1.84052903,
       1.90399555, 1.96746207, 2.03092858, 2.0943951 , 2.15786162,
       2.22132814, 2.28479466, 2.34826118, 2.41172769, 2.47519421,
       2.53866073, 2.60212725, 2.66559377, 2.72906028, 2.7925268 ,
       2.85599332, 2.91945984, 2.98292636, 3.04639288, 3.10985939,
       3.17332591, 3.23679243, 3.30025895, 3.36372547, 3.42719199,
       3.4906585 , 3.55412502, 3.61759154, 3.68105806, 3.74452458,
       3.8079911 , 3.87145761, 3.93492413, 3.99839065, 4.06185717,
       4.12532369, 4.1887902 , 4.25225672, 4.31572324, 4.37918976,
       4.44265628, 4.5061228 , 4.56958931, 4.63305583, 4.69652

In [36]:
# Import the libraries

import numpy as np 
import matplotlib.pyplot as plt

In [37]:
# Create a list

a = [[11, 12, 13], [21, 22, 23], [31, 32, 33]]
a

[[11, 12, 13], [21, 22, 23], [31, 32, 33]]

In [38]:
# Convert list to Numpy Array
# Every element is the same type

A = np.array(a)
A

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [39]:
# Show the numpy array dimensions

A.ndim

2

In [40]:
# Show the numpy array shape

A.shape

(3, 3)

In [41]:
# Show the numpy array size

A.size

9

In [42]:
# Access the element on the second row and third column

A[1, 2]

23

In [43]:
# Access the element on the second row and third column

A[1][2]

23

In [45]:
# Access the element on the first row and first and second columns

A[0][0:2]

array([11, 12])